spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baking?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:static

logging:
  level:
    cn.tedu.baking: debug

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true